name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3  # Important: Checkout the repository

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Use a custom theme file
          theme: |
            background: "#000000"  # Black background
            snake: "#FF0000"        # Red snake
            grid: "#8B0000"         # Darker red grid (optional)
            dots: "#FFA07A"         # Light Salmon for dots (optional)
